In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [18]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [19]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    for l in range(1,L):
        parameters["W"+str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b'+str(l)] = np.zeros((layer_dims[l],1))
    return parameters
         





In [20]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [21]:
def linear_forward(A_prev,w,b):
    return np.dot(w.T,A_prev)+b


In [22]:
def L_layer_forward(X,parameters):
    A = X
    L  = len(parameters)//2
    # Number of layers in the nural network
    for l in range(1,L+1):
        A_prev = A
        Wl = parameters["W"+str(l)]
        bl = parameters['b'+str(l)]
        # so we are passing the input with the Weights and the biases
        A = linear_forward(A_prev,Wl,bl)
        # the thing which we gave as the input and the result of the correponsding input
    return A,A_prev

In [23]:
X =df[['cgpa','profile_score']].values[0].reshape(2,1)
# Shape (no of features, no.training examples )
y  = df[['lpa']].values[0][0]
parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(X,parameters)

In [24]:
y_hat = y_hat[0][0]
print(y_hat)


0.32000000000000006


In [25]:
A1

array([[1.6],
       [1.6]])

In [26]:
print(df.shape)

(4, 3)


In [27]:
for j in range(df.shape[0]):
    y  = df.iloc[:,-1].values[j]
    print(y)
y

4
5
6
7


np.int64(7)

In [28]:
def update_parameters(parameters,gradients,lr=0.01):
    L = len(parameters)//2
    for  l in range(1,L+1):
        parameters["W"+str(1)]-=lr()

In [29]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [30]:
parameters = initialize_parameters([2,2,1])
epochs=1000
for i in range(epochs):
    Loss =[]
    for j in range(df.shape[0]):
        X = df.iloc[:,0:-1].values[j].reshape(2,1)
        y  = df.iloc[:,-1].values[j]
        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]
        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((y-y_hat)**2)
        print('Epochs - ',i+1,'Loss -',np.array(Loss).mean())
        
        

Epochs -  1 Loss - 13.542399999999997
Epochs -  1 Loss - 16.89375409265402
Epochs -  1 Loss - 20.955707689548415
Epochs -  1 Loss - 25.321744156025517
Epochs -  2 Loss - 8.94877628927336
Epochs -  2 Loss - 11.92790507630081
Epochs -  2 Loss - 15.17402050192277
Epochs -  2 Loss - 18.320004165722047
Epochs -  3 Loss - 3.6517788658308783
Epochs -  3 Loss - 5.567694642117171
Epochs -  3 Loss - 7.667763981701261
Epochs -  3 Loss - 9.473661050729628
Epochs -  4 Loss - 0.20571140374584412
Epochs -  4 Loss - 1.057996245285437
Epochs -  4 Loss - 2.2392733546195394
Epochs -  4 Loss - 3.2520938634031613
Epochs -  5 Loss - 0.5629279313986889
Epochs -  5 Loss - 0.36048507822026327
Epochs -  5 Loss - 0.804289112779833
Epochs -  5 Loss - 1.3407132589299962
Epochs -  6 Loss - 1.8884728910249873
Epochs -  6 Loss - 0.9465558215143977
Epochs -  6 Loss - 0.9190229241632863
Epochs -  6 Loss - 1.1726178458115697
Epochs -  7 Loss - 2.6115855941848722
Epochs -  7 Loss - 1.3346407381487548
Epochs -  7 Loss - 1

## Using Keras

In [31]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [72]:
model = Sequential()
model.add(Dense(2,input_dim=2))
model.add(Dense(1))

In [73]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [74]:
import numpy as np

In [75]:
model.get_weights()

[array([[-0.22453046, -0.6631434 ],
        [ 1.2161819 ,  1.0022005 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.47839773],
        [ 0.1258421 ]], dtype=float32),
 array([0.], dtype=float32)]

In [76]:
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]],dtype=np.float32),
                        np.array([0.,0.],dtype = np.float32),
                        np.array([[0.1],[0.1]],dtype=np.float32),
                        np.array([0.],dtype= np.float32)

                        ]

In [77]:
model.set_weights(new_weights)

In [78]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [79]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss="mse",optimizer=optimizer)

In [80]:
model.fit(df.iloc[:,0:-1].values,df.iloc[:,-1].values,epochs=100)

Epoch 1/100


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 568ms/step - loss: 28.0157
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 27.1864
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 26.2996
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 25.3581
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 24.3649
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 23.3234
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 22.2373
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 21.1108
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 19.9486
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 18.7560
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 17.5389
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 16.3036
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 15.0573
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 13.8080
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 12.5639
Epoch 16/100
1/

In [56]:
print(df.head())
print(df.iloc[:, -1].unique())
print(df.iloc[:, -1].min())
print(df.iloc[:, -1].max())

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7
[4 5 6 7]
4
7
